POST https://whycantthisshitwork.herokuapp.com/api/persons/
Content-Type: application/json

{
    "name": "kikkuli",
    "number": "55555555"
}

###
GET http://localhost:3001/api/persons/61dadda1c83c0466ff8cb81e

###

DELETE http://localhost:3001/api/persons/61dc1e033a3213a12fcd3d6b
